[build]
  command = "npm run build"
  publish = ".netlify/output"


[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production]
  branch = "main"

[context.ai-deploy]
  branch = "ai-deploy"
  environment = { NODE_ENV = "development" }
